export const signupConstants = {
    UPDATE_FIRST_NAME_INPUT: "UPDATE_FIRST_NAME_INPUT",
    UPDATE_LAST_NAME_INPUT: "UPDATE_LAST_NAME_INPUT",
    UPDATE_USERNAME_INPUT: "UPDATE_USERNAME_INPUT",
    UPDATE_PASSWORD_INPUT: "UPDATE_PASSWORD_INPUT",
    UPDATE_EMAIL_INPUT: "UPDATE_EMAIL_INPUT",
    UPDATE_AGE_INPUT: "UPDATE_AGE_INPUT",
    UPDATE_COUNTRY_INPUT: "UPDATE_COUNTRY_INPUT"
}