export const emailConstants = {
    UPDATE_EMAIL_INPUT: "UPDATE_EMAIL_INPUT",
    UPDATE_PASSWORD_INPUT: "UPDATE_PASSWORD_INPUT",
    EMAIL_EXISTS: "EMAIL_EXISTS",
    EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
    
}