export const userConstants = {

    //User registration/signup actions
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    //User login actions
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    //User logout action
    LOGOUT_REQUEST: 'LOGGING_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    //User session actions
    SESSION_REQUEST: "SESSION_REQUEST",
    SESSION_ACTIVE: "SESSION_ACTIVE",
    SESSION_NOT_FOUND: "SESSION_NOT_FOUND"

};